name: Start Program

on:
  push:
    branches:
      - fix/non-interactive
  workflow_dispatch:
    inputs:
      input_string:
        description: "Input string to pass to the program"
        required: true
        type: string

jobs:
  access-private-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Token
        run: |
          if [ ${#GITHUB_TOKEN} -eq 0 ]; then
            echo "GITHUB_TOKEN is empty or not set"
            exit 1
          else
            echo "GITHUB_TOKEN is set and has length ${#GITHUB_TOKEN}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.UBIQUITY_OS_CONFIGURATION_PAT }}

      - name: Access Private Repository TEST
        env:
          AUTH_TOKEN: ${{ secrets.UBIQUITY_OS_CONFIGURATION_PAT }}
        run: |
          git config --global url."https://$AUTH_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          # Test each repository URL
          echo "Testing ubiquity-os/ubiquibot-config"
          git ls-remote "https://$AUTH_TOKEN:x-oauth-basic@github.com/ubiquity-os/ubiquibot-config.git" HEAD || echo "Failed"
          echo "Testing ubiquity-os-marketplace/ubiquibot-config"
          git ls-remote "https://$AUTH_TOKEN:x-oauth-basic@github.com/ubiquity-os-marketplace/ubiquibot-config.git" HEAD || echo "Failed"
          echo "Testing ubiquity/ubiquibot-config"
          git ls-remote "https://$AUTH_TOKEN:x-oauth-basic@github.com/ubiquity/ubiquibot-config.git" HEAD || echo "Failed"
        continue-on-error: true
        id: test_access

      - name: Debug Token (DO NOT KEEP THIS IN PRODUCTION)
        run: |
          echo "Token starts with: ${AUTH_TOKEN:0:4}..."
          echo "Token length: ${#AUTH_TOKEN}"
        env:
          AUTH_TOKEN: ${{ secrets.UBIQUITY_OS_CONFIGURATION_PAT }}

      - name: Checkout code
        if: steps.test_access.outcome == 'success'
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: steps.test_access.outcome == 'success'
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install dependencies
        if: steps.test_access.outcome == 'success'
        run: npm install

      - name: Run npm start
        if: steps.test_access.outcome == 'success'
        run: npm start "${{ github.event_name == 'push' && 'change the max concurrent tasks for any role to be 1 max instead of 2' || github.event.inputs.input_string }}"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          INPUT_STRING: ${{ github.event_name == 'push' && 'change the max concurrent tasks for any role to be 1 max instead of 2' || github.event.inputs.input_string }}
          NON_INTERACTIVE: true
          AUTH_TOKEN: ${{ secrets.UBIQUITY_OS_CONFIGURATION_PAT }}
