name: Start Program

on:
  workflow_dispatch:
    inputs:
      input_string:
        description: "Input string to pass to the program"
        required: true
        type: string

jobs:
  run-npm-start:
    runs-on: ubuntu-latest
    steps:

      - name: Test Git Authentication
        env:
          AUTH_TOKEN: ${{ secrets.UBIQUITY_OS_CONFIGURATION_PAT }}
        run: |
          git config --global url."https://${{ secrets.UBIQUITY_OS_CONFIGURATION_PAT }}:@github.com/".insteadOf "https://github.com/"
          git ls-remote https://github.com/ubiquity-os-marketplace/ubiquibot-config.git HEAD

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install dependencies
        run: npm install

      - name: Run npm start
        run: npm start "${{ github.event.inputs.input_string }}"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          INPUT_STRING: ${{ github.event.inputs.input_string }}
          NON_INTERACTIVE: true
          AUTH_TOKEN: ${{ secrets.UBIQUITY_OS_CONFIGURATION_PAT }}