name: Start Program

on:
  workflow_dispatch:
    inputs:
      input_string:
        description: "Input string to pass to the program"
        required: true
        type: string

jobs:
  run-start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.UBIQUITY_OS_CONFIGURATION_AGENT_PAT }}
          persist-credentials: false  # Do not persist default credentials

      - name: Set up git authentication
        env:
          GITHUB_TOKEN: ${{ secrets.UBIQUITY_OS_CONFIGURATION_AGENT_PAT }}
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.UBIQUITY_OS_CONFIGURATION_AGENT_PAT }}:@github.com" > ~/.git-credentials

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install dependencies
        run: npm install

      - name: Run start script
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          INPUT_STRING: ${{ github.event.inputs.input_string }}
          NON_INTERACTIVE: "true"
          GITHUB_TOKEN: ${{ secrets.UBIQUITY_OS_CONFIGURATION_AGENT_PAT }}
        run: npm start "${{ github.event.inputs.input_string }}"